// Daftar emiten IDX yang dipantau. Kode yang tidak valid / sudah delisting otomatis dilewati
// saat scan. Tambah emiten sendiri lewat data/custom-tickers.json (array string, mis. ["ABCD"]).
const fs = require('fs');
const path = require('path');

const RAW = `
BBCA BBRI BMRI BBNI BRIS BBTN BNGA BDMN BNLI PNBN MEGA NISP BTPN BJBR BJTM BNII MAYA BABP BACA BBHI
BBKP BBMD BBSI BBYB BCIC BEKS BGTG BINA BKSW BMAS BNBA BSIM BSWD BTPS MCOR NOBU PNBS SDRA AGRO ARTO AMAR MASB
TLKM ISAT EXCL TOWR TBIG MTEL FREN LINK GOTO BUKA EMTK SCMA MNCN BELI DCII WIFI MLPT EDGE DMMX NFCX CYBR KIOS MTDL ATIC IRSX
ADRO ADMR AADI PTBA ITMG BUMI BYAN INDY HRUM MBMA MEDC PGAS AKRA ENRG ELSA RAJA ESSA BIPI DOID GEMS KKGI TOBA MYOH PTRO DSSA
UNTR ABMM BSSR SMMT CUAN PGEO BREN BRPT TPIA BRMS GTBO ARII APEX COAL INCO ANTM TINS MDKA NCKL HRTA PSAB DKFT AMMN NICL ZINC
CITA ARTI WINS TAMU RUIS SHIP PSSI BULL SOCI HITS LEAD TRAM MBSS TMAS SMDR ASSA GIAA BIRD BLTA NELY CMNP JSMR META
UNVR ICBP INDF MYOR CPIN JPFA MAIN KLBF SIDO MIKA HEAL SILO PRAY SAME CARE HMSP GGRM WIIM ULTJ CLEO AMRT MAPI MAPA ACES ERAA
LPPF RALS MPPA CSAP SMSM AUTO IMAS GJTL MASA INDS BRAM TSPC DVLA PYFA MERK KAEF INAF PEHA SOHO CINT ROTI GOOD CAMP HOKI FOOD
DLTA MLBI STTP KINO TCID UNIC ADES AISA TBLA LSIP AALI SIMP SGRO SSMS DSNG BWPT TAPG JAWA PALM ANJT CSRA BISI SMAR CEKA WMUU
BSDE CTRA SMRA PWON ASRI LPKR KIJA DMAS BEST JRPT MTLA PPRO DILD APLN BKSL GPRA RDTX MKPI MDLN PLIN CITY OMRE SMDM TRIN TARA
KBLV NZIA LCGP REAL INPP ELTY POLL DADA BAPA PURI POSA RISE BBSS HOMI
WIKA PTPP WSKT ADHI WTON WEGE TOTL ACST NRCA SSIA PBSA IDPR DGIK JKON TOTO SMGR INTP SMCB WSBP ARNA MLIA AMFG IKAI
KRAS ISSP GDST NIKL BAJA LION LMSH TPMA
ASII GDYR INDR SRIL TRIS PBRX BELL MYTX ARGO HEXA AMIN KAYU
INKP TKIM FASW SPMA ALDO KDSI BMHS IRRA SRAJ RSGK
BFIN ADMF CFIN PNLF LPGI AMAG PANS TRUE BCAP YULE VICO SMMA
DEWA KREN BNBR MLPL KPIG MARI HILL POOL FILM MSIN CMRY MAPB NASA ACRO KEJU ERTX BTEL BOLT SKYB
RATU ARCI MORA CBRE RAAM ASLI PTMP TOSK SMKL MAHA PGJO ESTA GOLL BLUE RELI CASA DOSS PORT CBMF
MBAP SGER BOSS PKPK PSGO DAYA ARKA ENAK PANI CBDK TRGU MDKI MLBI HRUM UANG SOTS SLIS OILS
INET IRRA NICL PNIN PTSN SIPD TEBE SKLT KMDS UNIQ BUDI PBID IGAR TRST TALF IPOL SPTO
`;

function load() {
  const set = new Set(RAW.split(/\s+/).filter(Boolean));
  try {
    const extra = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'custom-tickers.json'), 'utf8'));
    for (const t of extra) set.add(String(t).toUpperCase().replace(/\.JK$/, ''));
  } catch {}
  return [...set];
}

module.exports = { load };
